# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/UI Python/GUI_PyQt5_My_App/theme/deletefolder.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeleteFolder(object):
    def setupUi(self, DeleteFolder):
        DeleteFolder.setObjectName("DeleteFolder")
        DeleteFolder.resize(400, 86)
        DeleteFolder.setMinimumSize(QtCore.QSize(400, 86))
        DeleteFolder.setMaximumSize(QtCore.QSize(400, 86))
        DeleteFolder.setStyleSheet("background-color: rgb(237, 234, 255);")
        self.centralwidget = QtWidgets.QWidget(DeleteFolder)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(160, 60, 75, 23))
        font = QtGui.QFont()
        font.setFamily("MesloLGLDZ Nerd Font")
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"border:none;\n"
"border-radius:2px;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid #ba89ff ;\n"
"background-color: rgb(128, 44, 255);\n"
"}\n"
"QPushButton:hover{\n"
"border:none;\n"
"border-radius:3px;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px gray #6bd4c1 ;\n"
"background-color: rgb(160, 52, 255);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 361, 21))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(157, 0, 0);")
        self.label.setText("")
        self.label.setObjectName("label")
        DeleteFolder.setCentralWidget(self.centralwidget)

        self.retranslateUi(DeleteFolder)
        QtCore.QMetaObject.connectSlotsByName(DeleteFolder)

    def retranslateUi(self, DeleteFolder):
        _translate = QtCore.QCoreApplication.translate
        DeleteFolder.setWindowTitle(_translate("DeleteFolder", "Delete Category"))
        self.pushButton.setText(_translate("DeleteFolder", "Xác nhận"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DeleteFolder = QtWidgets.QMainWindow()
    ui = Ui_DeleteFolder()
    ui.setupUi(DeleteFolder)
    DeleteFolder.show()
    sys.exit(app.exec_())
