# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/UI Python/GUI_PyQt5_My_App/theme/HeaderView.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HeaderView(object):
    def setupUi(self, HeaderView):
        HeaderView.setObjectName("HeaderView")
        HeaderView.resize(462, 590)
        HeaderView.setMinimumSize(QtCore.QSize(462, 590))
        HeaderView.setMaximumSize(QtCore.QSize(462, 617))
        HeaderView.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(HeaderView)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("QCheckBox{\n"
"color:#ffffff;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    image: url(:/icons/png/icons8-select-24.png);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"image: url(:/icons/png/icons8-select-24_uncheck.png);\n"
"}\n"
"\n"
"QLabel{\n"
"color:#ffffff;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setStyleSheet("QFrame#frame_5{\n"
"background-color: rgb(38, 49, 98);\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_2 = QtWidgets.QFrame(self.frame_5)
        self.frame_2.setGeometry(QtCore.QRect(260, 20, 196, 521))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.A_ALL = QtWidgets.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MesloLGS Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.A_ALL.setFont(font)
        self.A_ALL.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.A_ALL.setChecked(True)
        self.A_ALL.setObjectName("A_ALL")
        self.verticalLayout_2.addWidget(self.A_ALL)
        self.ALL_LIVE = QtWidgets.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font Mono")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ALL_LIVE.setFont(font)
        self.ALL_LIVE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ALL_LIVE.setObjectName("ALL_LIVE")
        self.verticalLayout_2.addWidget(self.ALL_LIVE)
        self.A_DIE = QtWidgets.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font Mono")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.A_DIE.setFont(font)
        self.A_DIE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.A_DIE.setObjectName("A_DIE")
        self.verticalLayout_2.addWidget(self.A_DIE)
        self.A_CPPHONE = QtWidgets.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font Mono")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.A_CPPHONE.setFont(font)
        self.A_CPPHONE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.A_CPPHONE.setObjectName("A_CPPHONE")
        self.verticalLayout_2.addWidget(self.A_CPPHONE)
        self.A_CPXMDT = QtWidgets.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font Mono")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.A_CPXMDT.setFont(font)
        self.A_CPXMDT.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.A_CPXMDT.setObjectName("A_CPXMDT")
        self.verticalLayout_2.addWidget(self.A_CPXMDT)
        self.A_CP956 = QtWidgets.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font Mono")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.A_CP956.setFont(font)
        self.A_CP956.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.A_CP956.setObjectName("A_CP956")
        self.verticalLayout_2.addWidget(self.A_CP956)
        self.A_CP282 = QtWidgets.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font Mono")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.A_CP282.setFont(font)
        self.A_CP282.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.A_CP282.setObjectName("A_CP282")
        self.verticalLayout_2.addWidget(self.A_CP282)
        self.A_CPOTHER = QtWidgets.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font Mono")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.A_CPOTHER.setFont(font)
        self.A_CPOTHER.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.A_CPOTHER.setObjectName("A_CPOTHER")
        self.verticalLayout_2.addWidget(self.A_CPOTHER)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.OTHER = QtWidgets.QCheckBox(self.frame_3)
        self.OTHER.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font Mono")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.OTHER.setFont(font)
        self.OTHER.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.OTHER.setText("")
        self.OTHER.setObjectName("OTHER")
        self.horizontalLayout.addWidget(self.OTHER)
        self.TEXT_OTHER = QtWidgets.QComboBox(self.frame_3)
        self.TEXT_OTHER.setMinimumSize(QtCore.QSize(120, 27))
        self.TEXT_OTHER.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setBold(False)
        font.setWeight(50)
        self.TEXT_OTHER.setFont(font)
        self.TEXT_OTHER.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TEXT_OTHER.setStyleSheet("\n"
"QComboBox{\n"
"        border-radius:4px;\n"
"        padding-left: 10px;\n"
"        color: rgb(255, 255, 255);\n"
"        border: 0.5px solid #2c3a73;\n"
"    }\n"
"    QComboBox:hover{\n"
"        border: 0.5px solid #36468d;\n"
"        padding-left: 10px;\n"
"    }\n"
"      QComboBox::drop-down {\n"
"            width: 30px; \n"
"            border-left-color: #788dca;\n"
"            border-left-style: solid;\n"
"            border-top-right-radius: 2px;\n"
"            border-bottom-right-radius: 3px;    \n"
"            image: url(:/icons/png/cil-arrow-bottom.png);\n"
"            background-position: center;\n"
"            background-repeat: no-reperat;\n"
"            width: 16px;  /* Size of the arrow */\n"
"            height: 20px; /* Size of the arrow */\n"
"            top: 5px;     /* Adjust top position to center the icon */\n"
"         }\n"
"    \n"
"        QComboBox QAbstractItemView {\n"
"            color: rgb(255, 255, 255);\n"
"            background-color:#3d4c84;\n"
"            border:none;\n"
"            selection-background-color: #2c3871;\n"
"        }\n"
"    QComboBox:editable {\n"
"                    background: white;\n"
"                }\n"
"                QComboBox:!editable, QComboBox::drop-down:editable {\n"
"                   \n"
"           background-color: rgb(38, 49, 98);\n"
"                }\n"
"                QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"\n"
"                 background-color:#3c4b82;\n"
"                }\n"
"     QComboBox QAbstractItemView::item {\n"
"    border:none;\n"
"    background-color:#41518d;\n"
"                }\n"
"    ")
        self.TEXT_OTHER.setIconSize(QtCore.QSize(15, 15))
        self.TEXT_OTHER.setObjectName("TEXT_OTHER")
        self.TEXT_OTHER.addItem("")
        self.horizontalLayout.addWidget(self.TEXT_OTHER, 0, QtCore.Qt.AlignLeft)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setMinimumSize(QtCore.QSize(20, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignLeft)
        self.frame = QtWidgets.QFrame(self.frame_5)
        self.frame.setGeometry(QtCore.QRect(20, 20, 171, 531))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.UID = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("MesloLGS Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.UID.setFont(font)
        self.UID.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.UID.setChecked(True)
        self.UID.setObjectName("UID")
        self.verticalLayout.addWidget(self.UID)
        self.PASSWORD = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font Mono")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.PASSWORD.setFont(font)
        self.PASSWORD.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PASSWORD.setObjectName("PASSWORD")
        self.verticalLayout.addWidget(self.PASSWORD)
        self.CODE = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("MesloLGS Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.CODE.setFont(font)
        self.CODE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CODE.setObjectName("CODE")
        self.verticalLayout.addWidget(self.CODE)
        self.COOKIE = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("MesloLGS Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.COOKIE.setFont(font)
        self.COOKIE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.COOKIE.setObjectName("COOKIE")
        self.verticalLayout.addWidget(self.COOKIE)
        self.TOKEN = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font Mono")
        font.setBold(True)
        font.setWeight(75)
        self.TOKEN.setFont(font)
        self.TOKEN.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TOKEN.setObjectName("TOKEN")
        self.verticalLayout.addWidget(self.TOKEN)
        self.EMAIL = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("MesloLGS Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.EMAIL.setFont(font)
        self.EMAIL.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.EMAIL.setObjectName("EMAIL")
        self.verticalLayout.addWidget(self.EMAIL)
        self.PEMAIL = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("MesloLGS Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.PEMAIL.setFont(font)
        self.PEMAIL.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PEMAIL.setObjectName("PEMAIL")
        self.verticalLayout.addWidget(self.PEMAIL)
        self.USERAGENT = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("MesloLGS Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.USERAGENT.setFont(font)
        self.USERAGENT.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.USERAGENT.setObjectName("USERAGENT")
        self.verticalLayout.addWidget(self.USERAGENT)
        self.PROXY = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("MesloLGS Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.PROXY.setFont(font)
        self.PROXY.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PROXY.setChecked(True)
        self.PROXY.setObjectName("PROXY")
        self.verticalLayout.addWidget(self.PROXY)
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setGeometry(QtCore.QRect(260, 20, 161, 20))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel#label_2{\n"
"padding-bottom:5px;\n"
"border-bottom:1px solid #a27de1;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setGeometry(QtCore.QRect(20, 20, 131, 20))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel#label{\n"
"padding-bottom:5px;\n"
"border-bottom:1px solid #a27de1;\n"
"}")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.frame_5)
        HeaderView.setCentralWidget(self.centralwidget)

        self.retranslateUi(HeaderView)
        QtCore.QMetaObject.connectSlotsByName(HeaderView)

    def retranslateUi(self, HeaderView):
        _translate = QtCore.QCoreApplication.translate
        HeaderView.setWindowTitle(_translate("HeaderView", "Views Custom"))
        self.A_ALL.setText(_translate("HeaderView", "ALL"))
        self.ALL_LIVE.setText(_translate("HeaderView", "LIVE"))
        self.A_DIE.setText(_translate("HeaderView", "DIE"))
        self.A_CPPHONE.setText(_translate("HeaderView", "CHECKPOINT PHONE"))
        self.A_CPXMDT.setText(_translate("HeaderView", "CHECKPOINT XMDT"))
        self.A_CP956.setText(_translate("HeaderView", "CHECKPOINT 956"))
        self.A_CP282.setText(_translate("HeaderView", "CHECKPOINT 282"))
        self.A_CPOTHER.setText(_translate("HeaderView", "CHECKPOINT OTHER"))
        self.TEXT_OTHER.setItemText(0, _translate("HeaderView", "OTHERS"))
        self.UID.setText(_translate("HeaderView", "UID"))
        self.PASSWORD.setText(_translate("HeaderView", "PASSWORD"))
        self.CODE.setText(_translate("HeaderView", "QR CODE"))
        self.COOKIE.setText(_translate("HeaderView", "COOKIE"))
        self.TOKEN.setText(_translate("HeaderView", "API TOKEN"))
        self.EMAIL.setText(_translate("HeaderView", "EMAIL"))
        self.PEMAIL.setText(_translate("HeaderView", "PASS EMAIL"))
        self.USERAGENT.setText(_translate("HeaderView", "USER AGENT"))
        self.PROXY.setText(_translate("HeaderView", "PROXY"))
        self.label_2.setText(_translate("HeaderView", "Loại tài khoản"))
        self.label.setText(_translate("HeaderView", "Bảng hiển thị"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HeaderView = QtWidgets.QMainWindow()
    ui = Ui_HeaderView()
    ui.setupUi(HeaderView)
    HeaderView.show()
    sys.exit(app.exec_())
