# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/UI Python/GUI_PyQt5_My_App/theme/HeaderView.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HeaderView(object):
    def setupUi(self, HeaderView):
        HeaderView.setObjectName("HeaderView")
        HeaderView.resize(462, 617)
        HeaderView.setMinimumSize(QtCore.QSize(394, 617))
        HeaderView.setMaximumSize(QtCore.QSize(500, 617))
        HeaderView.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(HeaderView)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("QCheckBox{\n"
"color:#ffffff;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    image: url(:/icons/png/icons8-select-24.png);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"image: url(:/icons/png/icons8-select-24_uncheck.png);\n"
"}\n"
"\n"
"QLabel{\n"
"color:#ffffff;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setStyleSheet("QFrame#frame_5{\n"
"background-color: rgb(38, 49, 98);\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_2 = QtWidgets.QFrame(self.frame_5)
        self.frame_2.setGeometry(QtCore.QRect(250, 50, 196, 531))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_10 = QtWidgets.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MesloLGS Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_10.setFont(font)
        self.checkBox_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_10.setChecked(True)
        self.checkBox_10.setObjectName("checkBox_10")
        self.verticalLayout_2.addWidget(self.checkBox_10)
        self.checkBox_11 = QtWidgets.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font Mono")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.checkBox_11.setFont(font)
        self.checkBox_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_11.setObjectName("checkBox_11")
        self.verticalLayout_2.addWidget(self.checkBox_11)
        self.checkBox_12 = QtWidgets.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font Mono")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.checkBox_12.setFont(font)
        self.checkBox_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_12.setObjectName("checkBox_12")
        self.verticalLayout_2.addWidget(self.checkBox_12)
        self.checkBox_13 = QtWidgets.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font Mono")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.checkBox_13.setFont(font)
        self.checkBox_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_13.setObjectName("checkBox_13")
        self.verticalLayout_2.addWidget(self.checkBox_13)
        self.checkBox_21 = QtWidgets.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font Mono")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.checkBox_21.setFont(font)
        self.checkBox_21.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_21.setObjectName("checkBox_21")
        self.verticalLayout_2.addWidget(self.checkBox_21)
        self.checkBox_22 = QtWidgets.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font Mono")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.checkBox_22.setFont(font)
        self.checkBox_22.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.checkBox_22.setObjectName("checkBox_22")
        self.verticalLayout_2.addWidget(self.checkBox_22)
        self.checkBox_14 = QtWidgets.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font Mono")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.checkBox_14.setFont(font)
        self.checkBox_14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_14.setObjectName("checkBox_14")
        self.verticalLayout_2.addWidget(self.checkBox_14)
        self.checkBox_23 = QtWidgets.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font Mono")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.checkBox_23.setFont(font)
        self.checkBox_23.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_23.setObjectName("checkBox_23")
        self.verticalLayout_2.addWidget(self.checkBox_23)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_24 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_24.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font Mono")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.checkBox_24.setFont(font)
        self.checkBox_24.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_24.setText("")
        self.checkBox_24.setObjectName("checkBox_24")
        self.horizontalLayout.addWidget(self.checkBox_24)
        self.ComboboxFile = QtWidgets.QComboBox(self.frame_3)
        self.ComboboxFile.setMinimumSize(QtCore.QSize(120, 27))
        self.ComboboxFile.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setBold(False)
        font.setWeight(50)
        self.ComboboxFile.setFont(font)
        self.ComboboxFile.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ComboboxFile.setStyleSheet("\n"
"QComboBox{\n"
"        border-radius:4px;\n"
"        padding-left: 10px;\n"
"        color: rgb(255, 255, 255);\n"
"        border: 0.5px solid #2c3a73;\n"
"    }\n"
"    QComboBox:hover{\n"
"        border: 0.5px solid #36468d;\n"
"        padding-left: 10px;\n"
"    }\n"
"      QComboBox::drop-down {\n"
"            width: 30px; \n"
"            border-left-color: #788dca;\n"
"            border-left-style: solid;\n"
"            border-top-right-radius: 2px;\n"
"            border-bottom-right-radius: 3px;    \n"
"            image: url(:/icons/png/cil-arrow-bottom.png);\n"
"            background-position: center;\n"
"            background-repeat: no-reperat;\n"
"            width: 16px;  /* Size of the arrow */\n"
"            height: 20px; /* Size of the arrow */\n"
"            top: 5px;     /* Adjust top position to center the icon */\n"
"         }\n"
"    \n"
"        QComboBox QAbstractItemView {\n"
"            color: rgb(255, 255, 255);\n"
"            background-color:#3d4c84;\n"
"            border:none;\n"
"            selection-background-color: #2c3871;\n"
"        }\n"
"    QComboBox:editable {\n"
"                    background: white;\n"
"                }\n"
"                QComboBox:!editable, QComboBox::drop-down:editable {\n"
"                   \n"
"           background-color: rgb(38, 49, 98);\n"
"                }\n"
"                QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"\n"
"                 background-color:#3c4b82;\n"
"                }\n"
"     QComboBox QAbstractItemView::item {\n"
"    border:none;\n"
"    background-color:#41518d;\n"
"                }\n"
"    ")
        self.ComboboxFile.setIconSize(QtCore.QSize(15, 15))
        self.ComboboxFile.setObjectName("ComboboxFile")
        self.ComboboxFile.addItem("")
        self.horizontalLayout.addWidget(self.ComboboxFile, 0, QtCore.Qt.AlignLeft)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setMinimumSize(QtCore.QSize(20, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignLeft)
        self.frame = QtWidgets.QFrame(self.frame_5)
        self.frame.setGeometry(QtCore.QRect(10, 50, 171, 541))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("MesloLGS Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font Mono")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("MesloLGS Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("MesloLGS Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font Mono")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout.addWidget(self.checkBox_5)
        self.checkBox_7 = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("MesloLGS Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_7.setObjectName("checkBox_7")
        self.verticalLayout.addWidget(self.checkBox_7)
        self.checkBox_8 = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("MesloLGS Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_8.setObjectName("checkBox_8")
        self.verticalLayout.addWidget(self.checkBox_8)
        self.checkBox_9 = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("MesloLGS Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_9.setObjectName("checkBox_9")
        self.verticalLayout.addWidget(self.checkBox_9)
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("MesloLGS Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_6.setChecked(True)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout.addWidget(self.checkBox_6)
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setGeometry(QtCore.QRect(280, 30, 161, 20))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel#label_2{\n"
"padding-bottom:5px;\n"
"border-bottom:1px solid #a27de1;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setGeometry(QtCore.QRect(20, 30, 131, 20))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel#label{\n"
"padding-bottom:5px;\n"
"border-bottom:1px solid #a27de1;\n"
"}")
        self.label.setObjectName("label")
        self.btn_close = QtWidgets.QPushButton(self.frame_5)
        self.btn_close.setGeometry(QtCore.QRect(435, 5, 20, 20))
        self.btn_close.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_close.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_close.setStyleSheet("QPushButton{\n"
"background-color: rgb(38, 49, 98);\n"
"border:none;\n"
"border-radius:3px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(222, 61, 98);\n"
"border:none;\n"
"border-radius:3px;\n"
"}")
        self.btn_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/png/icons8-close-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_2.addWidget(self.frame_5)
        HeaderView.setCentralWidget(self.centralwidget)

        self.retranslateUi(HeaderView)
        QtCore.QMetaObject.connectSlotsByName(HeaderView)

    def retranslateUi(self, HeaderView):
        _translate = QtCore.QCoreApplication.translate
        HeaderView.setWindowTitle(_translate("HeaderView", "MainWindow"))
        self.checkBox_10.setText(_translate("HeaderView", "ALL"))
        self.checkBox_11.setText(_translate("HeaderView", "LIVE"))
        self.checkBox_12.setText(_translate("HeaderView", "DIE"))
        self.checkBox_13.setText(_translate("HeaderView", "CHECKPOINT PHONE"))
        self.checkBox_21.setText(_translate("HeaderView", "CHECKPOINT XMDT"))
        self.checkBox_22.setText(_translate("HeaderView", "CHECKPOINT 956"))
        self.checkBox_14.setText(_translate("HeaderView", "CHECKPOINT 282"))
        self.checkBox_23.setText(_translate("HeaderView", "CHECKPOINT OTHER"))
        self.ComboboxFile.setItemText(0, _translate("HeaderView", "OTHERS"))
        self.checkBox.setText(_translate("HeaderView", "UID"))
        self.checkBox_2.setText(_translate("HeaderView", "PASSWORD"))
        self.checkBox_3.setText(_translate("HeaderView", "QR CODE"))
        self.checkBox_4.setText(_translate("HeaderView", "COOKIE"))
        self.checkBox_5.setText(_translate("HeaderView", "API TOKEN"))
        self.checkBox_7.setText(_translate("HeaderView", "EMAIL"))
        self.checkBox_8.setText(_translate("HeaderView", "PASS EMAIL"))
        self.checkBox_9.setText(_translate("HeaderView", "USER AGENT"))
        self.checkBox_6.setText(_translate("HeaderView", "PROXY"))
        self.label_2.setText(_translate("HeaderView", "Loại tài khoản"))
        self.label.setText(_translate("HeaderView", "Bảng hiển thị"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HeaderView = QtWidgets.QMainWindow()
    ui = Ui_HeaderView()
    ui.setupUi(HeaderView)
    HeaderView.show()
    sys.exit(app.exec_())
