# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/UI Python/GUI_PyQt5_My_App/theme/newfolder.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateFolder(object):
    def setupUi(self, CreateFolder):
        CreateFolder.setObjectName("CreateFolder")
        CreateFolder.resize(490, 86)
        CreateFolder.setMinimumSize(QtCore.QSize(490, 86))
        CreateFolder.setMaximumSize(QtCore.QSize(490, 86))
        CreateFolder.setStyleSheet("background-color: rgb(237, 234, 255);")
        self.centralwidget = QtWidgets.QWidget(CreateFolder)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(40, 30, 201, 31))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"border:none;\n"
"border-radius:5px;\n"
"border: 1px solid #dddddd;\n"
"    background-color: rgb(255, 255, 255);\n"
"padding:5px;\n"
"}\n"
"QLineEdit:hover{\n"
"border:none;\n"
"border-radius:5px;\n"
"border: 1px solid #dddddd;\n"
"background-color: rgb(240, 255, 255);\n"
"padding:5px;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 91, 21))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(58, 89, 77);")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(370, 50, 75, 23))
        font = QtGui.QFont()
        font.setFamily("MesloLGLDZ Nerd Font")
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"border:none;\n"
"border-radius:2px;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid #ba89ff ;\n"
"background-color: rgb(128, 44, 255);\n"
"}\n"
"QPushButton:hover{\n"
"border:none;\n"
"border-radius:3px;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px gray #6bd4c1 ;\n"
"background-color: rgb(160, 52, 255);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        CreateFolder.setCentralWidget(self.centralwidget)

        self.retranslateUi(CreateFolder)
        QtCore.QMetaObject.connectSlotsByName(CreateFolder)

    def retranslateUi(self, CreateFolder):
        _translate = QtCore.QCoreApplication.translate
        CreateFolder.setWindowTitle(_translate("CreateFolder", "New Category"))
        self.label.setText(_translate("CreateFolder", "Tên Danh Mục"))
        self.pushButton.setText(_translate("CreateFolder", "Tạo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateFolder = QtWidgets.QMainWindow()
    ui = Ui_CreateFolder()
    ui.setupUi(CreateFolder)
    CreateFolder.show()
    sys.exit(app.exec_())
