# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/UI Python/GUI_PyQt5_My_App/theme/notice.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NotifiRemove(object):
    def setupUi(self, NotifiRemove):
        NotifiRemove.setObjectName("NotifiRemove")
        NotifiRemove.resize(395, 132)
        self.centralwidget = QtWidgets.QWidget(NotifiRemove)
        self.centralwidget.setStyleSheet("QFrame{\n"
"background-color: rgb(38, 49, 98);\n"
"\n"
"}\n"
"QFrame#frame{\n"
"border:1px solid #564a9e;\n"
"    color: rgb(180, 180, 200);\n"
"border-radius:3px;\n"
"}\n"
"QToolButton{\n"
"border:none;\n"
"background-color: rgb(89, 217, 236);\n"
"color: rgb(38, 49, 98);\n"
"border-radius:5px;\n"
"}\n"
"QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_yes = QtWidgets.QToolButton(self.frame)
        self.btn_yes.setGeometry(QtCore.QRect(220, 90, 51, 21))
        self.btn_yes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_yes.setObjectName("btn_yes")
        self.btn_no = QtWidgets.QToolButton(self.frame)
        self.btn_no.setGeometry(QtCore.QRect(290, 90, 51, 21))
        self.btn_no.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_no.setStyleSheet("background-color: rgb(255, 84, 129);")
        self.btn_no.setObjectName("btn_no")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 30, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.frame)
        NotifiRemove.setCentralWidget(self.centralwidget)

        self.retranslateUi(NotifiRemove)
        QtCore.QMetaObject.connectSlotsByName(NotifiRemove)

    def retranslateUi(self, NotifiRemove):
        _translate = QtCore.QCoreApplication.translate
        NotifiRemove.setWindowTitle(_translate("NotifiRemove", "MainWindow"))
        self.btn_yes.setText(_translate("NotifiRemove", "Yes"))
        self.btn_no.setText(_translate("NotifiRemove", "No"))
        self.label.setText(_translate("NotifiRemove", "Bạn có muốn xóa không ?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NotifiRemove = QtWidgets.QMainWindow()
    ui = Ui_NotifiRemove()
    ui.setupUi(NotifiRemove)
    NotifiRemove.show()
    sys.exit(app.exec_())
