# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/UI Python/GUI_PyQt5_My_App/theme/proxyitem.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Proxies_code(object):
    def setupUi(self, Proxies_code):
        Proxies_code.setObjectName("Proxies_code")
        Proxies_code.resize(561, 836)
        Proxies_code.setMinimumSize(QtCore.QSize(561, 836))
        Proxies_code.setMaximumSize(QtCore.QSize(561, 836))
        Proxies_code.setStyleSheet("background-color: rgb(237, 234, 255);")
        self.centralwidget = QtWidgets.QWidget(Proxies_code)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 380, 531, 391))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setStyleSheet("QPlainTextEdit{\n"
"background-color: rgb(252, 248, 255);\n"
"    color: rgb(93, 68, 73);\n"
"border-radius:5px;\n"
"}\n"
"QFrame{\n"
"border-radius:5px;\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
"border-radius:4px;\n"
"background-color: rgb(92, 203, 196);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"border:none;\n"
"border-radius:4px;\n"
"    background-color: rgb(98, 216, 208);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
" QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: rgba(255,255,255,255);\n"
"                height: 10px;\n"
"                margin: 0px 0px 0 0px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: rgba(255,255,255,255);\n"
"                height: 5px;\n"
"                margin: 0px 0px 0 0px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background-color: #d4d9d9;\n"
"                min-width: 10px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::add-line:horizontal {\n"
"                border: none;\n"
"                width: 0px;\n"
"                background-color: none;\n"
"            }\n"
"            QScrollBar::sub-line:horizontal {\n"
"                border: none;\n"
"                background: none;\n"
"                width: 0px;\n"
"            }\n"
"            QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar:vertical {\n"
"                border: none;\n"
"                background: rgba(255,255,255,255);\n"
"                width: 5px;\n"
"                margin: 0px 0 0px 0;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background-color: #c8c8c8;\n"
"                min-height: 20px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::add-line:vertical {\n"
"                border: none;\n"
"                background: none;\n"
"                height: 0px;\n"
"            }\n"
"            QScrollBar::sub-line:vertical {\n"
"                border: none;\n"
"                background: none;\n"
"                height: 0px;\n"
"            }\n"
"            QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: none;\n"
"            }")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.plainitem_script_get = QtWidgets.QPlainTextEdit(self.frame)
        self.plainitem_script_get.setGeometry(QtCore.QRect(10, 30, 511, 131))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.plainitem_script_get.setFont(font)
        self.plainitem_script_get.setStyleSheet("")
        self.plainitem_script_get.setObjectName("plainitem_script_get")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 211, 16))
        font = QtGui.QFont()
        font.setFamily("MesloLGLDZ Nerd Font")
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 41, 105);")
        self.label_4.setObjectName("label_4")
        self.proxyitem_check_get = QtWidgets.QPushButton(self.frame)
        self.proxyitem_check_get.setGeometry(QtCore.QRect(430, 170, 91, 23))
        font = QtGui.QFont()
        font.setFamily("MesloLGLDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.proxyitem_check_get.setFont(font)
        self.proxyitem_check_get.setObjectName("proxyitem_check_get")
        self.plainitem_script_change = QtWidgets.QPlainTextEdit(self.frame)
        self.plainitem_script_change.setGeometry(QtCore.QRect(10, 220, 511, 131))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.plainitem_script_change.setFont(font)
        self.plainitem_script_change.setStyleSheet("")
        self.plainitem_script_change.setObjectName("plainitem_script_change")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 200, 211, 16))
        font = QtGui.QFont()
        font.setFamily("MesloLGLDZ Nerd Font")
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 41, 105);")
        self.label_5.setObjectName("label_5")
        self.proxyitem_check_change = QtWidgets.QPushButton(self.frame)
        self.proxyitem_check_change.setGeometry(QtCore.QRect(430, 360, 91, 23))
        font = QtGui.QFont()
        font.setFamily("MesloLGLDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.proxyitem_check_change.setFont(font)
        self.proxyitem_check_change.setObjectName("proxyitem_check_change")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 20, 531, 331))
        self.frame_2.setStyleSheet("QPlainTextEdit{\n"
"background-color: rgb(252, 248, 255);\n"
"    color: rgb(93, 68, 73);\n"
"border-radius:5px;\n"
"}\n"
"QFrame{\n"
"border-radius:5px;\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
"border-radius:4px;\n"
"background-color: rgb(128, 44, 255);\n"
"color: rgb(255, 255, 255);\n"
"border:0.5px solid  #ff9dac;\n"
"}\n"
"QPushButton:hover{\n"
"border:none;\n"
"border-radius:4px;\n"
"    background-color: rgb(141, 65, 255);\n"
"color: rgb(255, 255, 255);\n"
"border:0.5px solid  #ff9dac;\n"
"}\n"
" QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: rgba(255,255,255,255);\n"
"                height: 10px;\n"
"                margin: 0px 0px 0 0px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: rgba(255,255,255,255);\n"
"                height: 5px;\n"
"                margin: 0px 0px 0 0px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background-color: #d4d9d9;\n"
"                min-width: 10px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::add-line:horizontal {\n"
"                border: none;\n"
"                width: 0px;\n"
"                background-color: none;\n"
"            }\n"
"            QScrollBar::sub-line:horizontal {\n"
"                border: none;\n"
"                background: none;\n"
"                width: 0px;\n"
"            }\n"
"            QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar:vertical {\n"
"                border: none;\n"
"                background: rgba(255,255,255,255);\n"
"                width: 5px;\n"
"                margin: 0px 0 0px 0;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background-color: #c8c8c8;\n"
"                min-height: 20px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::add-line:vertical {\n"
"                border: none;\n"
"                background: none;\n"
"                height: 0px;\n"
"            }\n"
"            QScrollBar::sub-line:vertical {\n"
"                border: none;\n"
"                background: none;\n"
"                height: 0px;\n"
"            }\n"
"            QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: none;\n"
"            }")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 181, 16))
        font = QtGui.QFont()
        font.setFamily("MesloLGSDZ Nerd Font")
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.plainitem_proxy = QtWidgets.QPlainTextEdit(self.frame_2)
        self.plainitem_proxy.setGeometry(QtCore.QRect(10, 40, 511, 101))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.plainitem_proxy.setFont(font)
        self.plainitem_proxy.setStyleSheet("QPlainTextEdit{\n"
"background-color: rgb(252, 248, 255);\n"
"color: rgb(163, 143, 212);\n"
"border-radius:5px;\n"
"border:0.5px solid #ffbdcd;\n"
"}\n"
"\n"
" QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: rgba(255,255,255,255);\n"
"                height: 10px;\n"
"                margin: 0px 0px 0 0px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: rgba(255,255,255,255);\n"
"                height: 5px;\n"
"                margin: 0px 0px 0 0px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background-color: #d4d9d9;\n"
"                min-width: 10px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::add-line:horizontal {\n"
"                border: none;\n"
"                width: 0px;\n"
"                background-color: none;\n"
"            }\n"
"            QScrollBar::sub-line:horizontal {\n"
"                border: none;\n"
"                background: none;\n"
"                width: 0px;\n"
"            }\n"
"            QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar:vertical {\n"
"                border: none;\n"
"                background: rgba(255,255,255,255);\n"
"                width: 5px;\n"
"                margin: 0px 0 0px 0;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background-color: #c8c8c8;\n"
"                min-height: 20px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::add-line:vertical {\n"
"                border: none;\n"
"                background: none;\n"
"                height: 0px;\n"
"            }\n"
"            QScrollBar::sub-line:vertical {\n"
"                border: none;\n"
"                background: none;\n"
"                height: 0px;\n"
"            }\n"
"            QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: none;\n"
"            }")
        self.plainitem_proxy.setObjectName("plainitem_proxy")
        self.plainitem_proxy_key = QtWidgets.QPlainTextEdit(self.frame_2)
        self.plainitem_proxy_key.setGeometry(QtCore.QRect(10, 180, 511, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.plainitem_proxy_key.setFont(font)
        self.plainitem_proxy_key.setStyleSheet("QPlainTextEdit{\n"
"background-color: rgb(252, 248, 255);\n"
"color: rgb(163, 143, 212);\n"
"border-radius:5px;\n"
"border:0.5px solid #ffbdcd;\n"
"}\n"
"\n"
" QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: rgba(255,255,255,255);\n"
"                height: 10px;\n"
"                margin: 0px 0px 0 0px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: rgba(255,255,255,255);\n"
"                height: 5px;\n"
"                margin: 0px 0px 0 0px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background-color: #d4d9d9;\n"
"                min-width: 10px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::add-line:horizontal {\n"
"                border: none;\n"
"                width: 0px;\n"
"                background-color: none;\n"
"            }\n"
"            QScrollBar::sub-line:horizontal {\n"
"                border: none;\n"
"                background: none;\n"
"                width: 0px;\n"
"            }\n"
"            QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar:vertical {\n"
"                border: none;\n"
"                background: rgba(255,255,255,255);\n"
"                width: 5px;\n"
"                margin: 0px 0 0px 0;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background-color: #c8c8c8;\n"
"                min-height: 20px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::add-line:vertical {\n"
"                border: none;\n"
"                background: none;\n"
"                height: 0px;\n"
"            }\n"
"            QScrollBar::sub-line:vertical {\n"
"                border: none;\n"
"                background: none;\n"
"                height: 0px;\n"
"            }\n"
"            QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: none;\n"
"            }")
        self.plainitem_proxy_key.setObjectName("plainitem_proxy_key")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(10, 270, 521, 16))
        font = QtGui.QFont()
        font.setFamily("MesloLGSDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 160, 181, 16))
        font = QtGui.QFont()
        font.setFamily("MesloLGSDZ Nerd Font")
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(210, 790, 111, 41))
        self.frame_3.setStyleSheet("QPlainTextEdit{\n"
"background-color: rgb(252, 248, 255);\n"
"    color: rgb(93, 68, 73);\n"
"border-radius:5px;\n"
"}\n"
"QFrame{\n"
"border-radius:5px;\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
"border-radius:4px;\n"
"background-color: rgb(128, 44, 255);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"border:none;\n"
"border-radius:4px;\n"
"    background-color: rgb(141, 65, 255);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
" QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: rgba(255,255,255,255);\n"
"                height: 10px;\n"
"                margin: 0px 0px 0 0px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: rgba(255,255,255,255);\n"
"                height: 5px;\n"
"                margin: 0px 0px 0 0px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background-color: #d4d9d9;\n"
"                min-width: 10px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::add-line:horizontal {\n"
"                border: none;\n"
"                width: 0px;\n"
"                background-color: none;\n"
"            }\n"
"            QScrollBar::sub-line:horizontal {\n"
"                border: none;\n"
"                background: none;\n"
"                width: 0px;\n"
"            }\n"
"            QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar:vertical {\n"
"                border: none;\n"
"                background: rgba(255,255,255,255);\n"
"                width: 5px;\n"
"                margin: 0px 0 0px 0;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background-color: #c8c8c8;\n"
"                min-height: 20px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::add-line:vertical {\n"
"                border: none;\n"
"                background: none;\n"
"                height: 0px;\n"
"            }\n"
"            QScrollBar::sub-line:vertical {\n"
"                border: none;\n"
"                background: none;\n"
"                height: 0px;\n"
"            }\n"
"            QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: none;\n"
"            }")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.proxyitem_confirm = QtWidgets.QPushButton(self.frame_3)
        self.proxyitem_confirm.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("MesloLGLDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.proxyitem_confirm.setFont(font)
        self.proxyitem_confirm.setObjectName("proxyitem_confirm")
        self.horizontalLayout.addWidget(self.proxyitem_confirm)
        Proxies_code.setCentralWidget(self.centralwidget)

        self.retranslateUi(Proxies_code)
        QtCore.QMetaObject.connectSlotsByName(Proxies_code)

    def retranslateUi(self, Proxies_code):
        _translate = QtCore.QCoreApplication.translate
        Proxies_code.setWindowTitle(_translate("Proxies_code", "CUSTOM PROXIES"))
        self.plainitem_script_get.setPlaceholderText(_translate("Proxies_code", "# PYTHON"))
        self.label_4.setText(_translate("Proxies_code", "SCRIPT GET PROXIES "))
        self.proxyitem_check_get.setText(_translate("Proxies_code", "CHECK SCRIPT"))
        self.plainitem_script_change.setPlaceholderText(_translate("Proxies_code", "# PYTHON"))
        self.label_5.setText(_translate("Proxies_code", "SCRIPT CHANGE PROXIES "))
        self.proxyitem_check_change.setText(_translate("Proxies_code", "CHECK SCRIPT"))
        self.label_6.setText(_translate("Proxies_code", "<html><head/><body><p><span style=\" color:#2e15aa;\">DANH SÁCH PROXY</span></p></body></html>"))
        self.plainitem_proxy.setPlaceholderText(_translate("Proxies_code", "  Nhập PROXY"))
        self.plainitem_proxy_key.setPlaceholderText(_translate("Proxies_code", "  Nhập API KEY "))
        self.label_2.setText(_translate("Proxies_code", "<html><head/><body><p><span style=\" font-style:italic; color:#714099;\">#</span><span style=\" font-style:italic; color:#d33a5c;\">note</span> :<span style=\" font-style:italic;\"/><span style=\" font-weight:400; font-style:italic; color:#7440a8;\">mỗi API 1 dòng duy nhất, tất cả API sẽ chia đều để chạy từng tác vụ</span></p></body></html>"))
        self.label.setText(_translate("Proxies_code", "<html><head/><body><p><span style=\" color:#2e15aa;\">DANH SÁCH API KEY PROXY</span></p></body></html>"))
        self.proxyitem_confirm.setText(_translate("Proxies_code", "CONFIRM"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Proxies_code = QtWidgets.QMainWindow()
    ui = Ui_Proxies_code()
    ui.setupUi(Proxies_code)
    Proxies_code.show()
    sys.exit(app.exec_())
