# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/UI Python/GUI_PyQt5_My_App/theme/tabwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(986, 443)
        TabWidget.setMaximumSize(QtCore.QSize(986, 443))
        self.centralwidget = QtWidgets.QWidget(TabWidget)
        self.centralwidget.setMinimumSize(QtCore.QSize(986, 443))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 443))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameMain = QtWidgets.QFrame(self.centralwidget)
        self.frameMain.setStyleSheet("background-color: rgb(78, 90, 121);")
        self.frameMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMain.setObjectName("frameMain")
        self.tabWidget = QtWidgets.QTabWidget(self.frameMain)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 981, 441))
        font = QtGui.QFont()
        font.setFamily("MesloLGLDZ Nerd Font")
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet(" QTabWidget::pane {\n"
"                font-weight: bold;\n"
"                color: rgb(255, 255, 255);\n"
"                border: 1px solid  rgb(225, 229, 255);\n"
"                background-color: rgb(78, 90, 121);\n"
"                border-radius:3px;\n"
"border:none;\n"
"            }\n"
" QTabBar::tab {\n"
"                background-color: rgb(78, 90, 121);\n"
"                color: rgb(255, 255, 255);\n"
"                padding: 10px;\n"
"                font-weight: bold;\n"
"                border-bottom: none;\n"
"                min-width: 100px;\n"
"            }\n"
"\n"
"QTabBar::tab:selected {\n"
"                border:none;\n"
"                  background-color: rgb(78, 90, 121);\n"
"                font-weight: bold;\n"
"                border-bottom:2px  solid rgb(79, 181, 178);\n"
"                color: rgb(255, 255, 255);\n"
"            }\n"
"\n"
"QTabBar::tab:hover {\n"
"                background-color: rgb(78, 90, 121);        \n"
"                border-radius:3px;\n"
"                color: rgb(255, 255, 255);\n"
"            }")
        self.tabWidget.setObjectName("tabWidget")
        self.TabAddItems = QtWidgets.QWidget()
        self.TabAddItems.setObjectName("TabAddItems")
        self.plain_item = QtWidgets.QPlainTextEdit(self.TabAddItems)
        self.plain_item.setGeometry(QtCore.QRect(10, 20, 941, 171))
        font = QtGui.QFont()
        font.setFamily("MesloLGSDZ Nerd Font")
        font.setPointSize(8)
        self.plain_item.setFont(font)
        self.plain_item.setStyleSheet("QWidget{\n"
"background-color: rgb(237, 234, 255);\n"
"}\n"
"QPlainTextEdit{\n"
"background-color: rgb(78, 90, 121);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"padding:5px;\n"
"border:1px solid rgb(190, 190, 190);;\n"
"}\n"
"QPlainTextEdit:hover{\n"
"background-color: rgb(95, 110, 147);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"border:1px solid #e1e4ff;\n"
"}\n"
"QFrame{\n"
"border-radius:5px;\n"
"}\n"
" QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: rgba(255,255,255,255);\n"
"                height: 10px;\n"
"                margin: 0px 0px 0 0px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: rgba(255,255,255,255);\n"
"                height: 5px;\n"
"                margin: 0px 0px 0 0px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background-color: #d4d9d9;\n"
"                min-width: 10px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::add-line:horizontal {\n"
"                border: none;\n"
"                width: 0px;\n"
"                background-color: none;\n"
"            }\n"
"            QScrollBar::sub-line:horizontal {\n"
"                border: none;\n"
"                background: none;\n"
"                width: 0px;\n"
"            }\n"
"            QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar:vertical {\n"
"                border: none;\n"
"                background: rgba(255,255,255,255);\n"
"                width: 5px;\n"
"                margin: 0px 0 0px 0;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background-color: #c8c8c8;\n"
"                min-height: 20px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::add-line:vertical {\n"
"                border: none;\n"
"                background: none;\n"
"                height: 0px;\n"
"            }\n"
"            QScrollBar::sub-line:vertical {\n"
"                border: none;\n"
"                background: none;\n"
"                height: 0px;\n"
"            }\n"
"            QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: none;\n"
"            }")
        self.plain_item.setTabChangesFocus(True)
        self.plain_item.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plain_item.setPlainText("")
        self.plain_item.setBackgroundVisible(False)
        self.plain_item.setCenterOnScroll(True)
        self.plain_item.setObjectName("plain_item")
        self.frame = QtWidgets.QFrame(self.TabAddItems)
        self.frame.setGeometry(QtCore.QRect(10, 210, 941, 91))
        self.frame.setStyleSheet("QComboBox {\n"
"    background-color: rgb(78, 90, 121);\n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QFrame#frame {\n"
"    border: 1px solid rgb(190, 190, 190);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QFrame#frame:hover {\n"
"    border: 1px solid #e1e4ff;\n"
"    border-radius: 4px;\n"
"    background-color: rgb(245, 242, 255);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 10px; \n"
"    border-left-color: #788dca;\n"
"    border-left-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    border-top-right-radius: 2px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    image: url(:/icons/png/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    border-radius: 4px;\n"
"   margin-left: -4px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: rgb(78, 90, 121);\n"
"    color: rgb(255, 255, 255); /* White text color */\n"
"    border: none; /* No border */\n"
"     selection-background-color: rgb(135, 155, 208);\n"
"    selection-color: rgb(255, 255, 255); /* Selected item text color */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QComboBox::item {\n"
"    background-color: transparent; /* Ensure background is transparent */\n"
"    color: rgb(255, 255, 255); /* White text color */\n"
"    border-radius: 4px; /* Apply rounded borders */\n"
"}\n"
"\n"
"QComboBox::item:selected {\n"
"    background-color: rgb(190, 190, 190); /* Light background on selection */\n"
"    color: rgb(255, 255, 255); /* Maintain text color */\n"
"    border-radius: 4px; /* Ensure rounded borders are applied */\n"
"}\n"
"\n"
"QComboBox::item:focus {\n"
"    outline: none; /* Remove focus outline */\n"
"}\n"
"\n"
"\n"
" QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: rgba(255,255,255,255);\n"
"                height: 10px;\n"
"                margin: 0px 0px 0 0px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: rgba(255,255,255,255);\n"
"                height: 5px;\n"
"                margin: 0px 0px 0 0px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background-color: #d4d9d9;\n"
"                min-width: 10px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::add-line:horizontal {\n"
"                border: none;\n"
"                width: 0px;\n"
"                background-color: none;\n"
"            }\n"
"            QScrollBar::sub-line:horizontal {\n"
"                border: none;\n"
"                background: none;\n"
"                width: 0px;\n"
"            }\n"
"            QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar:vertical {\n"
"                border: none;\n"
"                background: rgba(255,255,255,255);\n"
"                width: 5px;\n"
"                margin: 0px 0 0px 0;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background-color: #c8c8c8;\n"
"                min-height: 20px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::add-line:vertical {\n"
"                border: none;\n"
"                background: none;\n"
"                height: 0px;\n"
"            }\n"
"            QScrollBar::sub-line:vertical {\n"
"                border: none;\n"
"                background: none;\n"
"                height: 0px;\n"
"            }\n"
"            QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: none;\n"
"            }")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 39))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.frame_4.setFont(font)
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.combox_1 = QtWidgets.QComboBox(self.frame_4)
        self.combox_1.setMinimumSize(QtCore.QSize(0, 19))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.combox_1.setFont(font)
        self.combox_1.setObjectName("combox_1")
        self.horizontalLayout_2.addWidget(self.combox_1)
        self.combox_2 = QtWidgets.QComboBox(self.frame_4)
        self.combox_2.setMinimumSize(QtCore.QSize(0, 19))
        font = QtGui.QFont()
        font.setFamily("MesloLGSDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combox_2.setFont(font)
        self.combox_2.setObjectName("combox_2")
        self.horizontalLayout_2.addWidget(self.combox_2)
        self.combox_3 = QtWidgets.QComboBox(self.frame_4)
        self.combox_3.setMinimumSize(QtCore.QSize(0, 19))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combox_3.setFont(font)
        self.combox_3.setObjectName("combox_3")
        self.horizontalLayout_2.addWidget(self.combox_3)
        self.combox_4 = QtWidgets.QComboBox(self.frame_4)
        self.combox_4.setMinimumSize(QtCore.QSize(0, 19))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combox_4.setFont(font)
        self.combox_4.setObjectName("combox_4")
        self.horizontalLayout_2.addWidget(self.combox_4)
        self.combox_5 = QtWidgets.QComboBox(self.frame_4)
        self.combox_5.setMinimumSize(QtCore.QSize(0, 19))
        font = QtGui.QFont()
        font.setFamily("MesloLGSDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combox_5.setFont(font)
        self.combox_5.setObjectName("combox_5")
        self.horizontalLayout_2.addWidget(self.combox_5)
        self.combox_6 = QtWidgets.QComboBox(self.frame_4)
        self.combox_6.setMinimumSize(QtCore.QSize(0, 19))
        font = QtGui.QFont()
        font.setFamily("MesloLGSDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combox_6.setFont(font)
        self.combox_6.setObjectName("combox_6")
        self.horizontalLayout_2.addWidget(self.combox_6)
        self.combox_7 = QtWidgets.QComboBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("MesloLGLDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combox_7.setFont(font)
        self.combox_7.setObjectName("combox_7")
        self.horizontalLayout_2.addWidget(self.combox_7)
        self.combox_8 = QtWidgets.QComboBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("MesloLGLDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combox_8.setFont(font)
        self.combox_8.setObjectName("combox_8")
        self.horizontalLayout_2.addWidget(self.combox_8)
        self.combox_9 = QtWidgets.QComboBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("MesloLGLDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combox_9.setFont(font)
        self.combox_9.setObjectName("combox_9")
        self.horizontalLayout_2.addWidget(self.combox_9)
        self.combox_10 = QtWidgets.QComboBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("MesloLGLDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combox_10.setFont(font)
        self.combox_10.setObjectName("combox_10")
        self.horizontalLayout_2.addWidget(self.combox_10)
        self.combox_11 = QtWidgets.QComboBox(self.frame_4)
        self.combox_11.setMinimumSize(QtCore.QSize(0, 19))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combox_11.setFont(font)
        self.combox_11.setObjectName("combox_11")
        self.horizontalLayout_2.addWidget(self.combox_11)
        self.combox_12 = QtWidgets.QComboBox(self.frame_4)
        self.combox_12.setMinimumSize(QtCore.QSize(0, 19))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combox_12.setFont(font)
        self.combox_12.setObjectName("combox_12")
        self.horizontalLayout_2.addWidget(self.combox_12)
        self.combox_13 = QtWidgets.QComboBox(self.frame_4)
        self.combox_13.setMinimumSize(QtCore.QSize(0, 19))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combox_13.setFont(font)
        self.combox_13.setObjectName("combox_13")
        self.horizontalLayout_2.addWidget(self.combox_13)
        self.combox_14 = QtWidgets.QComboBox(self.frame_4)
        self.combox_14.setMinimumSize(QtCore.QSize(0, 19))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combox_14.setFont(font)
        self.combox_14.setObjectName("combox_14")
        self.horizontalLayout_2.addWidget(self.combox_14)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 39))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 12, 101, 25))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"background-color: rgb(100, 115, 154);\n"
"padding:5px;\n"
"border:0.5px solid #576486;")
        self.label.setObjectName("label")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(130, 12, 219, 25))
        self.frame_3.setStyleSheet("QFrame#frame_3{\n"
"color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"background-color: rgb(100, 115, 154);\n"
"padding:5px;\n"
"border:0.5px solid #576486;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(100, 115, 154);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.combo_account = QtWidgets.QComboBox(self.frame_6)
        self.combo_account.setGeometry(QtCore.QRect(0, -4, 119, 20))
        self.combo_account.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MesloLGSDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combo_account.setFont(font)
        self.combo_account.setStyleSheet("QComboBox{\n"
"color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"background-color: rgb(100, 115, 154);\n"
"padding:5px;\n"
"border:0.5px solid #576486;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px; \n"
"    border-left-color: #788dca;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 2px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }")
        self.combo_account.setObjectName("combo_account")
        self.combo_account.addItem("")
        self.combo_account.addItem("")
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setGeometry(QtCore.QRect(520, 10, 191, 25))
        self.frame_5.setStyleSheet("QFrame#frame_5{\n"
"color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"background-color: rgb(100, 115, 154);\n"
"padding:5px;\n"
"border:0.5px solid #576486;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(100, 115, 154);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3, 0, QtCore.Qt.AlignVCenter)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.combo_danhmuc = QtWidgets.QComboBox(self.frame_7)
        self.combo_danhmuc.setGeometry(QtCore.QRect(0, -4, 131, 20))
        self.combo_danhmuc.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("MesloLGSDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combo_danhmuc.setFont(font)
        self.combo_danhmuc.setStyleSheet("QComboBox{\n"
"color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"background-color: rgb(100, 115, 154);\n"
"padding:5px;\n"
"border:0.5px solid #576486;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px; \n"
"    border-left-color: #788dca;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 2px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }")
        self.combo_danhmuc.setObjectName("combo_danhmuc")
        self.horizontalLayout_4.addWidget(self.frame_7)
        self.frame_9 = QtWidgets.QFrame(self.frame_2)
        self.frame_9.setGeometry(QtCore.QRect(480, 29, 41, 61))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.frame_8 = QtWidgets.QFrame(self.frame_2)
        self.frame_8.setGeometry(QtCore.QRect(720, 10, 179, 25))
        self.frame_8.setStyleSheet("QFrame#frame_8{\n"
"color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"background-color: rgb(100, 115, 154);\n"
"padding:5px;\n"
"border:0.5px solid #576486;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setMaximumSize(QtCore.QSize(55, 16777215))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(100, 115, 154);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_10.setStyleSheet("background-color: rgb(100, 115, 154);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.combo_ua = QtWidgets.QComboBox(self.frame_10)
        self.combo_ua.setGeometry(QtCore.QRect(0, -4, 121, 20))
        self.combo_ua.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("MesloLGSDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combo_ua.setFont(font)
        self.combo_ua.setStyleSheet("QComboBox{\n"
"color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"background-color: rgb(100, 115, 154);\n"
"padding:5px;\n"
"border:0.5px solid #576486;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px; \n"
"    border-left-color: #788dca;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 2px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }")
        self.combo_ua.setObjectName("combo_ua")
        self.combo_ua.addItem("")
        self.combo_ua.addItem("")
        self.combo_ua.addItem("")
        self.horizontalLayout_5.addWidget(self.frame_10)
        self.verticalLayout.addWidget(self.frame_2)
        self.item_close = QtWidgets.QPushButton(self.TabAddItems)
        self.item_close.setGeometry(QtCore.QRect(790, 350, 61, 25))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.item_close.setFont(font)
        self.item_close.setStyleSheet("\n"
"QPushButton{\n"
"border:none;\n"
"border-radius:2px;\n"
"background-color: rgb(111, 128, 172);\n"
"color: rgb(244, 255, 250);\n"
"}\n"
"QPushButton:hover{\n"
"border:none;\n"
"border-radius:3px;\n"
"    color: rgb(244, 255, 250);\n"
"    background-color: rgb(127, 147, 197);\n"
"}")
        self.item_close.setObjectName("item_close")
        self.item_add = QtWidgets.QPushButton(self.TabAddItems)
        self.item_add.setGeometry(QtCore.QRect(870, 350, 61, 25))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.item_add.setFont(font)
        self.item_add.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"border:none;\n"
"border-radius:2px;\n"
"background-color: rgb(113, 194, 194);\n"
"color: rgb(255, 233, 253);\n"
"}\n"
"QPushButton:hover{\n"
"border:none;\n"
"border-radius:3px;\n"
"color: rgb(255, 233, 253);\n"
"    background-color: rgb(120, 206, 206);\n"
"}")
        self.item_add.setObjectName("item_add")
        self.tabWidget.addTab(self.TabAddItems, "")
        self.TabProxy = QtWidgets.QWidget()
        self.TabProxy.setObjectName("TabProxy")
        self.tabWidget.addTab(self.TabProxy, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout.addWidget(self.frameMain)
        TabWidget.setCentralWidget(self.centralwidget)

        self.retranslateUi(TabWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "MainWindow"))
        self.plain_item.setPlaceholderText(_translate("TabWidget", "Nhập tài khoản"))
        self.label.setText(_translate("TabWidget", "TOTAL:  0"))
        self.label_2.setText(_translate("TabWidget", "ACCOUNT TYPE:"))
        self.combo_account.setItemText(0, _translate("TabWidget", "FACEBOOK"))
        self.combo_account.setItemText(1, _translate("TabWidget", "INSTAGRAM"))
        self.label_3.setText(_translate("TabWidget", "FOLDER: "))
        self.label_4.setText(_translate("TabWidget", "TYPE UA:"))
        self.combo_ua.setItemText(0, _translate("TabWidget", "Windows"))
        self.combo_ua.setItemText(1, _translate("TabWidget", "IOS"))
        self.combo_ua.setItemText(2, _translate("TabWidget", "Android"))
        self.item_close.setText(_translate("TabWidget", "Đóng"))
        self.item_add.setText(_translate("TabWidget", "Tạo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabAddItems), _translate("TabWidget", "Nhập tài khoản"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabProxy), _translate("TabWidget", "Nhập Proxy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("TabWidget", "Thư mục"))
import icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabWidget = QtWidgets.QMainWindow()
    ui = Ui_TabWidget()
    ui.setupUi(TabWidget)
    TabWidget.show()
    sys.exit(app.exec_())
