# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/UI Python/GUI_PyQt5_My_App/theme/tabwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(986, 443)
        TabWidget.setMaximumSize(QtCore.QSize(986, 443))
        self.centralwidget = QtWidgets.QWidget(TabWidget)
        self.centralwidget.setMinimumSize(QtCore.QSize(986, 443))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 443))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameMain = QtWidgets.QFrame(self.centralwidget)
        self.frameMain.setMinimumSize(QtCore.QSize(0, 0))
        self.frameMain.setMaximumSize(QtCore.QSize(985, 443))
        self.frameMain.setStyleSheet("background-color: rgb(38, 49, 98);")
        self.frameMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMain.setObjectName("frameMain")
        self.tabWidget = QtWidgets.QTabWidget(self.frameMain)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 981, 441))
        font = QtGui.QFont()
        font.setFamily("MesloLGLDZ Nerd Font")
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet(" QTabWidget::pane {\n"
"                font-weight: bold;\n"
"                color: rgb(255, 255, 255);\n"
"                border: 1px solid  rgb(225, 229, 255);\n"
"                background-color: rgb(253, 247, 255);\n"
"                border-radius:3px;\n"
"                border:none;\n"
"            }\n"
" QTabBar::tab {\n"
"                background-color: #263162;\n"
"                color: rgb(201, 223, 255);\n"
"                padding: 10px;\n"
"                font-weight: bold;\n"
"                border-bottom: none;\n"
"                min-width: 100px;\n"
"            }\n"
"\n"
"QTabBar::tab:selected {\n"
"                border:none;\n"
"                background-color:#263162;\n"
"                 color: rgb(201, 223, 255);\n"
"                font-weight: bold;\n"
"                border-bottom:2px  solid rgb(79, 181, 178);\n"
"            }\n"
"\n"
"QTabBar::tab:hover {\n"
"                background-color: #263162;\n"
"                color: #748dc7;\n"
"                border-radius:3px;\n"
"            }\n"
"\n"
"\n"
"QFrame#frame {\n"
"    border: 1px solid #5e70a7;\n"
"    background-color: rgb(29, 52, 104);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QFrame#frame:hover {\n"
"    border: 1px solid #415485 ;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 10px; \n"
"    border-left-color: #788dca;\n"
"    border-left-style: solid;\n"
"    color: rgb(85, 98, 131);\n"
"    border-top-right-radius: 2px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    image: url(:/icons/png/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    border-radius: 4px;\n"
"   margin-left: -4px;\n"
"}\n"
"QComboBox{\n"
"color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"background-color: rgb(29, 52, 104);\n"
"padding:5px;\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"   background-color: rgb(253, 247, 255);\n"
"    color: rgb(85, 98, 131);\n"
"    border: none; /* No border */\n"
"     selection-background-color: #e0e3f7;\n"
"    selection-color: rgb(85, 98, 131); /* Selected item text color */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QComboBox::item {\n"
"    background-color: transparent; /* Ensure background is transparent */\n"
"   color: rgb(85, 98, 131); /* White text color */\n"
"    border-radius: 4px; /* Apply rounded borders */\n"
"}\n"
"\n"
"QComboBox::item:selected {\n"
"    background-color: rgb(190, 190, 190); /* Light background on selection */\n"
"    color: rgb(255, 255, 255); /* Maintain text color */\n"
"    border-radius: 4px; /* Ensure rounded borders are applied */\n"
"}\n"
"\n"
"QComboBox::item:focus {\n"
"    outline: none; /* Remove focus outline */\n"
"}\n"
"\n"
"\n"
" QScrollBar:horizontal {\n"
"                border: none;\n"
"               background-color: rgb(150, 173, 232);\n"
"                height: 5px;\n"
"                margin: 0px 0px 0 0px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"            background-color: rgb(150, 173, 232);\n"
"\n"
"                height: 3px;\n"
"                margin: 0px 0px 0 0px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                 background-color: rgb(105, 122, 163);\n"
"               \n"
"                min-width: 2px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::add-line:horizontal {\n"
"                border: none;\n"
"                width: 0px;\n"
"                background-color: none;\n"
"            }\n"
"            QScrollBar::sub-line:horizontal {\n"
"                border: none;\n"
"                background: none;\n"
"                width: 0px;\n"
"            }\n"
"            QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar:vertical {\n"
"                border: none;\n"
"                background-color: rgb(105, 122, 163);\n"
"\n"
"                width: 3px;\n"
"                margin: 0px 0 0px 0;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background-color: rgb(150, 173, 232);\n"
"                min-height: 5px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QScrollBar::add-line:vertical {\n"
"                border: none;\n"
"                background: none;\n"
"                height: 0px;\n"
"            }\n"
"            QScrollBar::sub-line:vertical {\n"
"                border: none;\n"
"                background: none;\n"
"                height: 0px;\n"
"            }\n"
"            QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: none;\n"
"            }")
        self.tabWidget.setObjectName("tabWidget")
        self.TabAddItems = QtWidgets.QWidget()
        self.TabAddItems.setObjectName("TabAddItems")
        self.plain_item = QtWidgets.QPlainTextEdit(self.TabAddItems)
        self.plain_item.setGeometry(QtCore.QRect(10, 20, 941, 171))
        font = QtGui.QFont()
        font.setFamily("MesloLGSDZ Nerd Font")
        font.setPointSize(8)
        self.plain_item.setFont(font)
        self.plain_item.setStyleSheet("\n"
"QPlainTextEdit{\n"
"background-color:rgba(29,52,104,255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"padding:5px;\n"
"border:1px solid  #5e70a7;\n"
"}\n"
"QPlainTextEdit:hover{\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"border:1px solid  #415485;\n"
"}\n"
"QFrame{\n"
"border-radius:5px;\n"
"}\n"
"")
        self.plain_item.setTabChangesFocus(True)
        self.plain_item.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plain_item.setPlainText("")
        self.plain_item.setBackgroundVisible(False)
        self.plain_item.setCenterOnScroll(True)
        self.plain_item.setObjectName("plain_item")
        self.frame = QtWidgets.QFrame(self.TabAddItems)
        self.frame.setGeometry(QtCore.QRect(10, 210, 941, 91))
        self.frame.setStyleSheet("background-color: rgb(29, 52, 104);\n"
"color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 39))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.frame_4.setFont(font)
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.combox_1 = QtWidgets.QComboBox(self.frame_4)
        self.combox_1.setMinimumSize(QtCore.QSize(0, 19))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.combox_1.setFont(font)
        self.combox_1.setObjectName("combox_1")
        self.horizontalLayout_2.addWidget(self.combox_1)
        self.combox_2 = QtWidgets.QComboBox(self.frame_4)
        self.combox_2.setMinimumSize(QtCore.QSize(0, 19))
        font = QtGui.QFont()
        font.setFamily("MesloLGSDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combox_2.setFont(font)
        self.combox_2.setObjectName("combox_2")
        self.horizontalLayout_2.addWidget(self.combox_2)
        self.combox_3 = QtWidgets.QComboBox(self.frame_4)
        self.combox_3.setMinimumSize(QtCore.QSize(0, 19))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combox_3.setFont(font)
        self.combox_3.setObjectName("combox_3")
        self.horizontalLayout_2.addWidget(self.combox_3)
        self.combox_4 = QtWidgets.QComboBox(self.frame_4)
        self.combox_4.setMinimumSize(QtCore.QSize(0, 19))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combox_4.setFont(font)
        self.combox_4.setObjectName("combox_4")
        self.horizontalLayout_2.addWidget(self.combox_4)
        self.combox_5 = QtWidgets.QComboBox(self.frame_4)
        self.combox_5.setMinimumSize(QtCore.QSize(0, 19))
        font = QtGui.QFont()
        font.setFamily("MesloLGSDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combox_5.setFont(font)
        self.combox_5.setObjectName("combox_5")
        self.horizontalLayout_2.addWidget(self.combox_5)
        self.combox_6 = QtWidgets.QComboBox(self.frame_4)
        self.combox_6.setMinimumSize(QtCore.QSize(0, 19))
        font = QtGui.QFont()
        font.setFamily("MesloLGSDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combox_6.setFont(font)
        self.combox_6.setObjectName("combox_6")
        self.horizontalLayout_2.addWidget(self.combox_6)
        self.combox_7 = QtWidgets.QComboBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("MesloLGLDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combox_7.setFont(font)
        self.combox_7.setObjectName("combox_7")
        self.horizontalLayout_2.addWidget(self.combox_7)
        self.combox_8 = QtWidgets.QComboBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("MesloLGLDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combox_8.setFont(font)
        self.combox_8.setObjectName("combox_8")
        self.horizontalLayout_2.addWidget(self.combox_8)
        self.combox_9 = QtWidgets.QComboBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("MesloLGLDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combox_9.setFont(font)
        self.combox_9.setObjectName("combox_9")
        self.horizontalLayout_2.addWidget(self.combox_9)
        self.combox_10 = QtWidgets.QComboBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("MesloLGLDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combox_10.setFont(font)
        self.combox_10.setObjectName("combox_10")
        self.horizontalLayout_2.addWidget(self.combox_10)
        self.combox_11 = QtWidgets.QComboBox(self.frame_4)
        self.combox_11.setMinimumSize(QtCore.QSize(0, 19))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combox_11.setFont(font)
        self.combox_11.setObjectName("combox_11")
        self.horizontalLayout_2.addWidget(self.combox_11)
        self.combox_12 = QtWidgets.QComboBox(self.frame_4)
        self.combox_12.setMinimumSize(QtCore.QSize(0, 19))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combox_12.setFont(font)
        self.combox_12.setObjectName("combox_12")
        self.horizontalLayout_2.addWidget(self.combox_12)
        self.combox_13 = QtWidgets.QComboBox(self.frame_4)
        self.combox_13.setMinimumSize(QtCore.QSize(0, 19))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combox_13.setFont(font)
        self.combox_13.setObjectName("combox_13")
        self.horizontalLayout_2.addWidget(self.combox_13)
        self.combox_14 = QtWidgets.QComboBox(self.frame_4)
        self.combox_14.setMinimumSize(QtCore.QSize(0, 19))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combox_14.setFont(font)
        self.combox_14.setObjectName("combox_14")
        self.horizontalLayout_2.addWidget(self.combox_14)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 39))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(20, 10, 101, 25))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"    QLabel {\n"
"      color: rgb(255, 255, 255);\n"
"        border-radius: 5px;\n"
"       background-color: rgb(29, 52, 104);\n"
"        padding: 5px;\n"
"        border: 0.5px solid #5e70a7;\n"
"    }\n"
"    QLabel:hover {\n"
"      color: rgb(255, 255, 255);\n"
"        border-radius: 5px;\n"
"       background-color: rgb(29, 52, 104);\n"
"        padding: 5px;\n"
"        border: 0.5px solid #415485;\n"
"    }")
        self.label.setObjectName("label")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(130, 12, 219, 25))
        self.frame_3.setStyleSheet("\n"
"    QFrame#frame_3 {\n"
"        border-radius: 5px;\n"
"        background-color: rgb(29, 52, 104);  \n"
"        padding: 5px;\n"
"        color: rgb(255, 255, 255);\n"
"        border: 0.5px solid #5e70a7;\n"
"    }\n"
"    QFrame#frame_3:hover {\n"
"        color: rgb(255, 255, 255);\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"        border: 0.5px solid #415485;\n"
"    }\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(29, 52, 104);\n"
"")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.combo_account = QtWidgets.QComboBox(self.frame_6)
        self.combo_account.setGeometry(QtCore.QRect(0, -4, 119, 20))
        self.combo_account.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MesloLGSDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combo_account.setFont(font)
        self.combo_account.setStyleSheet("QComboBox{\n"
"color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"background-color: rgb(29, 52, 104);\n"
"padding:5px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px; \n"
"    border-left-color: #788dca;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 2px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"\n"
"\n"
"")
        self.combo_account.setObjectName("combo_account")
        self.combo_account.addItem("")
        self.combo_account.addItem("")
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setGeometry(QtCore.QRect(530, 10, 201, 25))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        self.frame_5.setFont(font)
        self.frame_5.setStyleSheet("\n"
"    QFrame#frame_5 {\n"
"        color: rgb(87, 100, 173);\n"
"        border-radius: 5px;\n"
"        background-color: rgb(29, 52, 104);\n"
"        padding: 5px;\n"
"        border: 0.5px solid #5e70a7;\n"
"    }\n"
"    QFrame#frame_5:hover {\n"
"        color: rgb(255, 255, 255);\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"        border: 0.5px solid #415485;\n"
"    }")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setGeometry(QtCore.QRect(5, 2, 50, 21))
        self.label_3.setMinimumSize(QtCore.QSize(0, 19))
        self.label_3.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(29, 52, 104);")
        self.label_3.setObjectName("label_3")
        self.combo_danhmuc = QtWidgets.QComboBox(self.frame_5)
        self.combo_danhmuc.setGeometry(QtCore.QRect(60, 3, 131, 20))
        self.combo_danhmuc.setMinimumSize(QtCore.QSize(100, 19))
        font = QtGui.QFont()
        font.setFamily("MesloLGSDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combo_danhmuc.setFont(font)
        self.combo_danhmuc.setStyleSheet("QComboBox{\n"
"color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"background-color: rgb(29, 52, 104);\n"
"padding:5px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px; \n"
"    border-left-color: #788dca;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 2px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"\n"
"\n"
"")
        self.combo_danhmuc.setObjectName("combo_danhmuc")
        self.frame_9 = QtWidgets.QFrame(self.frame_2)
        self.frame_9.setGeometry(QtCore.QRect(480, 29, 41, 61))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.frame_8 = QtWidgets.QFrame(self.frame_2)
        self.frame_8.setGeometry(QtCore.QRect(740, 10, 179, 25))
        self.frame_8.setStyleSheet("\n"
"    QFrame#frame_8 {\n"
"        color: rgb(87, 100, 173);\n"
"        border-radius: 5px;\n"
"        background-color: rgb(29, 52, 104);\n"
"        padding: 5px;\n"
"        border: 0.5px solid #5e70a7;\n"
"    }\n"
"    QFrame#frame_8:hover {\n"
"        color: rgb(255, 255, 255);\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"        border: 0.5px solid #415485;\n"
"    }")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setGeometry(QtCore.QRect(5, 2, 70, 21))
        self.label_4.setMinimumSize(QtCore.QSize(0, 19))
        self.label_4.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(29, 52, 104);")
        self.label_4.setObjectName("label_4")
        self.combo_ua = QtWidgets.QComboBox(self.frame_8)
        self.combo_ua.setGeometry(QtCore.QRect(61, 1, 112, 21))
        self.combo_ua.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("MesloLGSDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combo_ua.setFont(font)
        self.combo_ua.setStyleSheet("QComboBox{\n"
"color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"background-color: rgb(29, 52, 104);\n"
"padding:5px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px; \n"
"    border-left-color: #788dca;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 2px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"\n"
"\n"
"")
        self.combo_ua.setObjectName("combo_ua")
        self.combo_ua.addItem("")
        self.combo_ua.addItem("")
        self.combo_ua.addItem("")
        self.verticalLayout.addWidget(self.frame_2)
        self.item_close = QtWidgets.QPushButton(self.TabAddItems)
        self.item_close.setGeometry(QtCore.QRect(790, 350, 61, 25))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.item_close.setFont(font)
        self.item_close.setStyleSheet("\n"
"QPushButton{\n"
"border:none;\n"
"border-radius:2px;\n"
"background-color: rgb(111, 128, 172);\n"
"color: rgb(244, 255, 250);\n"
"}\n"
"QPushButton:hover{\n"
"border:none;\n"
"border-radius:3px;\n"
"    color: rgb(244, 255, 250);\n"
"    background-color: rgb(127, 147, 197);\n"
"}")
        self.item_close.setObjectName("item_close")
        self.item_add = QtWidgets.QPushButton(self.TabAddItems)
        self.item_add.setGeometry(QtCore.QRect(870, 350, 61, 25))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.item_add.setFont(font)
        self.item_add.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"border:none;\n"
"border-radius:2px;\n"
"background-color: #29b7a5;\n"
"color: rgb(255, 233, 253);\n"
"}\n"
"QPushButton:hover{\n"
"border:none;\n"
"border-radius:3px;\n"
"color: rgb(255, 233, 253);\n"
"background-color: #2bc2ae;\n"
"}")
        self.item_add.setObjectName("item_add")
        self.tabWidget.addTab(self.TabAddItems, "")
        self.TabProxy = QtWidgets.QWidget()
        self.TabProxy.setObjectName("TabProxy")
        self.frame_11 = QtWidgets.QFrame(self.TabProxy)
        self.frame_11.setGeometry(QtCore.QRect(0, 0, 981, 341))
        self.frame_11.setStyleSheet("")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.plain_proxy = QtWidgets.QPlainTextEdit(self.frame_11)
        self.plain_proxy.setGeometry(QtCore.QRect(0, 50, 311, 91))
        font = QtGui.QFont()
        font.setFamily("MesloLGSDZ Nerd Font")
        font.setPointSize(8)
        self.plain_proxy.setFont(font)
        self.plain_proxy.setStyleSheet("\n"
"QPlainTextEdit{\n"
"background-color:rgba(29,52,104,255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"padding:5px;\n"
"border:1px solid  #5e70a7;\n"
"}\n"
"QPlainTextEdit:hover{\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"border:1px solid  #415485;\n"
"}\n"
"QFrame{\n"
"border-radius:5px;\n"
"}\n"
"")
        self.plain_proxy.setTabChangesFocus(True)
        self.plain_proxy.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plain_proxy.setPlainText("")
        self.plain_proxy.setBackgroundVisible(False)
        self.plain_proxy.setCenterOnScroll(True)
        self.plain_proxy.setObjectName("plain_proxy")
        self.combo_proxy = QtWidgets.QComboBox(self.frame_11)
        self.combo_proxy.setGeometry(QtCore.QRect(0, 10, 311, 23))
        self.combo_proxy.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MesloLGSDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.combo_proxy.setFont(font)
        self.combo_proxy.setStyleSheet("QComboBox{\n"
"color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"background-color: rgb(29, 52, 104);\n"
"padding:5px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px; \n"
"    border-left-color: #788dca;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 2px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"background-color: rgb(29, 52, 104);\n"
"    color: rgb(255, 255, 255);\n"
"    border: none; /* No border */\n"
"     selection-background-color: #e0e3f7;\n"
"    selection-color: rgb(85, 98, 131); /* Selected item text color */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QComboBox::item {\n"
"    background-color: transparent; /* Ensure background is transparent */\n"
"   color: rgb(85, 98, 131); /* White text color */\n"
"    border-radius: 4px; /* Apply rounded borders */\n"
"}\n"
"\n"
"QComboBox::item:selected {\n"
"    background-color: rgb(190, 190, 190); /* Light background on selection */\n"
"    color: rgb(255, 255, 255); /* Maintain text color */\n"
"    border-radius: 4px; /* Ensure rounded borders are applied */\n"
"}")
        self.combo_proxy.setObjectName("combo_proxy")
        self.combo_proxy.addItem("")
        self.combo_proxy.addItem("")
        self.combo_proxy.addItem("")
        self.combo_proxy.addItem("")
        self.item_closeProxy = QtWidgets.QPushButton(self.TabProxy)
        self.item_closeProxy.setGeometry(QtCore.QRect(790, 350, 61, 25))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.item_closeProxy.setFont(font)
        self.item_closeProxy.setStyleSheet("\n"
"QPushButton{\n"
"border:none;\n"
"border-radius:2px;\n"
"background-color: rgb(111, 128, 172);\n"
"color: rgb(244, 255, 250);\n"
"}\n"
"QPushButton:hover{\n"
"border:none;\n"
"border-radius:3px;\n"
"    color: rgb(244, 255, 250);\n"
"    background-color: rgb(127, 147, 197);\n"
"}")
        self.item_closeProxy.setObjectName("item_closeProxy")
        self.item_addProxy = QtWidgets.QPushButton(self.TabProxy)
        self.item_addProxy.setGeometry(QtCore.QRect(870, 350, 61, 25))
        font = QtGui.QFont()
        font.setFamily("MesloLGMDZ Nerd Font")
        font.setBold(True)
        font.setWeight(75)
        self.item_addProxy.setFont(font)
        self.item_addProxy.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"border:none;\n"
"border-radius:2px;\n"
"background-color: #29b7a5;\n"
"color: rgb(255, 233, 253);\n"
"}\n"
"QPushButton:hover{\n"
"border:none;\n"
"border-radius:3px;\n"
"color: rgb(255, 233, 253);\n"
"background-color: #2bc2ae;\n"
"}")
        self.item_addProxy.setObjectName("item_addProxy")
        self.tabWidget.addTab(self.TabProxy, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout.addWidget(self.frameMain)
        TabWidget.setCentralWidget(self.centralwidget)

        self.retranslateUi(TabWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "MainWindow"))
        self.plain_item.setPlaceholderText(_translate("TabWidget", "Nhập tài khoản"))
        self.label.setText(_translate("TabWidget", "TOTAL:  0"))
        self.label_2.setText(_translate("TabWidget", "ACCOUNT TYPE:"))
        self.combo_account.setItemText(0, _translate("TabWidget", "FACEBOOK"))
        self.combo_account.setItemText(1, _translate("TabWidget", "INSTAGRAM"))
        self.label_3.setText(_translate("TabWidget", "FOLDER: "))
        self.label_4.setText(_translate("TabWidget", "TYPE UA:"))
        self.combo_ua.setItemText(0, _translate("TabWidget", "Windows"))
        self.combo_ua.setItemText(1, _translate("TabWidget", "IOS"))
        self.combo_ua.setItemText(2, _translate("TabWidget", "Android"))
        self.item_close.setText(_translate("TabWidget", "Đóng"))
        self.item_add.setText(_translate("TabWidget", "Tạo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabAddItems), _translate("TabWidget", "Nhập tài khoản"))
        self.plain_proxy.setPlaceholderText(_translate("TabWidget", "Nhập Proxy"))
        self.combo_proxy.setItemText(0, _translate("TabWidget", "HTTP Proxy"))
        self.combo_proxy.setItemText(1, _translate("TabWidget", "Socks 4 Proxy"))
        self.combo_proxy.setItemText(2, _translate("TabWidget", "Socks 5 Proxy"))
        self.combo_proxy.setItemText(3, _translate("TabWidget", "Free Proxy"))
        self.item_closeProxy.setText(_translate("TabWidget", "Đóng"))
        self.item_addProxy.setText(_translate("TabWidget", "Tạo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabProxy), _translate("TabWidget", "Nhập Proxy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("TabWidget", "Thư mục"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabWidget = QtWidgets.QMainWindow()
    ui = Ui_TabWidget()
    ui.setupUi(TabWidget)
    TabWidget.show()
    sys.exit(app.exec_())
